[2024-01-27 15:43:49,633: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 15:43:49,648: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 15:43:49,690: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 15:43:49,692: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 15:43:50,701: INFO/MainProcess] mingle: all alone
[2024-01-27 15:43:50,716: INFO/MainProcess] celery@fd4779c2adcd ready.
[2024-01-27 16:05:13,275: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:05:13,293: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 16:05:13,295: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:05:13,299: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 16:05:14,310: INFO/MainProcess] mingle: all alone
[2024-01-27 16:05:14,322: INFO/MainProcess] celery@fd4779c2adcd ready.
[2024-01-27 16:05:59,724: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:05:59,739: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 16:05:59,741: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:05:59,745: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 16:06:00,754: INFO/MainProcess] mingle: all alone
[2024-01-27 16:06:00,764: INFO/MainProcess] celery@fd4779c2adcd ready.
[2024-01-27 16:11:04,935: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:11:04,950: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 16:11:04,952: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:11:04,954: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 16:11:05,964: INFO/MainProcess] mingle: all alone
[2024-01-27 16:11:05,991: INFO/MainProcess] celery@902e2393b6a6 ready.
[2024-01-27 16:18:31,852: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:18:31,871: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 16:18:31,873: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:18:31,876: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 16:18:32,887: INFO/MainProcess] mingle: all alone
[2024-01-27 16:18:32,900: INFO/MainProcess] celery@902e2393b6a6 ready.
[2024-01-27 16:23:54,250: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:23:54,266: INFO/MainProcess] Connected to redis://redis:6379/0
[2024-01-27 16:23:54,268: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-27 16:23:54,271: INFO/MainProcess] mingle: searching for neighbors
[2024-01-27 16:23:55,281: INFO/MainProcess] mingle: all alone
[2024-01-27 16:23:55,294: INFO/MainProcess] celery@902e2393b6a6 ready.
[2024-01-27 16:30:09,406: INFO/MainProcess] Task modules.services.tasks.send_activate_email_message_task[3f9a5fa4-4a6b-452c-a407-44c28cbc36c1] received
[2024-01-27 16:30:10,863: INFO/ForkPoolWorker-7] Task modules.services.tasks.send_activate_email_message_task[3f9a5fa4-4a6b-452c-a407-44c28cbc36c1] succeeded in 1.455071083999428s: None
[2024-01-28 12:29:34,549: WARNING/MainProcess] /usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-01-28 12:29:39,565: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 2.00 seconds... (1/100)

[2024-01-28 12:29:46,571: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 4.00 seconds... (2/100)

[2024-01-28 12:29:55,577: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 6.00 seconds... (3/100)

[2024-01-28 12:30:06,582: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 8.00 seconds... (4/100)

[2024-01-28 12:30:19,590: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 10.00 seconds... (5/100)

[2024-01-28 12:30:34,596: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 12.00 seconds... (6/100)

[2024-01-28 12:30:51,603: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 14.00 seconds... (7/100)

[2024-01-28 12:31:10,609: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 16.00 seconds... (8/100)

[2024-01-28 12:31:31,617: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 18.00 seconds... (9/100)

[2024-01-28 12:31:54,625: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 20.00 seconds... (10/100)

[2024-01-28 12:32:19,632: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 22.00 seconds... (11/100)

[2024-01-28 12:32:46,640: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 24.00 seconds... (12/100)

[2024-01-28 12:33:15,650: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 26.00 seconds... (13/100)

[2024-01-28 12:33:46,659: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 28.00 seconds... (14/100)

[2024-01-28 12:34:19,668: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 30.00 seconds... (15/100)

[2024-01-28 12:34:54,678: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:35:31,686: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:36:08,695: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:36:45,706: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:37:22,716: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:37:59,724: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:38:36,734: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:39:13,741: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:39:50,750: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:40:27,759: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:41:04,769: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:41:41,778: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:42:18,787: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:42:55,796: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:43:32,809: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:44:09,820: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:44:46,829: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:45:23,837: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:46:00,846: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:46:37,855: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:47:14,865: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:47:51,875: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:48:28,884: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:49:05,893: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:49:42,902: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:50:19,911: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:50:56,919: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:51:33,928: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:52:10,937: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:52:47,945: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:53:24,955: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:54:01,963: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:54:38,973: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:55:15,981: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:55:52,991: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:56:30,000: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:57:07,009: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:57:44,018: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:58:21,027: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:58:58,036: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 12:59:35,044: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:00:12,052: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:00:49,061: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:01:26,071: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:02:03,080: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:02:40,090: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:03:17,099: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:03:54,108: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:04:31,116: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:05:08,126: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:05:45,134: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

[2024-01-28 13:06:22,144: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Try again..
Trying again in 32.00 seconds... (16/100)

